# Generated by Django 3.2.8 on 2021-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TKB',
            fields=[
                ('class_name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('TKB_content', models.CharField(default=',,,,,\n,,,,,\n,,,,,\n,,,,,\n,,,,,', max_length=1000)),
                ('gv_toan', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_van', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_anh', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_ly', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_hoa', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_sinh', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_gdcd', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_su', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_dia', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_the_duc', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_quoc_phong', models.CharField(default='Nguyễn Văn A', max_length=100)),
                ('gv_tin', models.CharField(default='Nguyễn Văn A', max_length=100)),
            ],
        ),
    ]
