# Generated by Django 3.2.8 on 2021-11-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkb',
            name='TKB_content',
            field=models.TextField(default=',,,,,\n,,,,,\n,,,,,\n,,,,,\n,,,,,', max_length=1000),
        ),
    ]
