# Generated by Django 3.2.8 on 2021-11-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tkb_tkb_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tkb',
            name='gv_anh',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_dia',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_gdcd',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_hoa',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_ly',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_quoc_phong',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_sinh',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_su',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_the_duc',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_tin',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_toan',
        ),
        migrations.RemoveField(
            model_name='tkb',
            name='gv_van',
        ),
    ]
