# Generated by Django 3.2.8 on 2021-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211107_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFeed',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
