# Generated by Django 3.2.8 on 2021-11-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newfeed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newfeed',
            options={'ordering': ['-publish_date']},
        ),
    ]
