# Generated by Django 3.2.8 on 2021-11-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_newfeed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfeed',
            name='loi_hs',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
