# Generated by Django 3.2.8 on 2021-11-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_newfeed_loi_hs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfeed',
            name='loi_hs',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
